# Site settings
title: Front End Development, UI, UX & Design - k3no.com
description: Front End Development, UI, UX & Design Posts - Eugenio N. Leon - Santa Barbara California - Keno -  www.k3no.com
baseurl: /Front-End-Web-Dev-UI-UX
#url: "https://kenoleon.github.io" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
highlighter: rouge

# Build settings
exclude:
  - README.md

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
